### ISSUE TITLE
Приветствую 0шибка 10008 при verify

### ISSUE THREAD

**Issue by masscontrolx** [borrowwing/emotion#1]
Приветствую, респект и уважение за сие добро. И вот этот код на главной и при вводе кода(с смс), а после ввода добавляется ещё Ошибка №100028 при verify :

Session file contains:

Array
(
    [key] => cda634f07357e228c7bc19f18476d2e7
    [msisdn] => 79***016442
)

Ошибка №100028 при verify

**Comment by masscontrolx** [comment]
> Ошибка №100028 при verify
посмотрел логи ошибок и в функции изменил путь к tmp  и создал дирректорию tmp рядом с файлами, стало работать через 2-3 раза

**Comment by devnulldevzero** [comment]
Принято, спасибо за issue. Продебажу проблему, сделаю обновление.
